# Generated by Django 4.0.6 on 2022-07-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=150),
        ),
    ]
