# Generated by Django 4.0.6 on 2022-07-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0003_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
